---
  - name: Set up LXC container for a TRAEFIK
    hosts: all # here should be tsc-host-1 instead
    become: yes
    vars_files:
      - vars.yml
    #vars:
    #  DEST: TRAEFIK  # remove this line if "--extra-vars "DEST=TRAEFIK" is passed when calling ansible-playbook

    tasks:
      - name: Install LXC
        apt:
          name: lxc
          state: present
          update_cache: yes

      # - name: Uncomment LXC_DHCP_CONFILE in dnsmasq.conf
      #   lineinfile:
      #     path: /etc/default/lxc-net
      #     regexp: '^#LXC_DHCP_CONFILE'
      #     line: 'LXC_DHCP_CONFILE=/etc/dnsmasq.conf'

      - name: Ensure the directory for SSH keys exists
        file:
          path: "{{ playbook_dir }}/files/ssh-keys/{{ DEST }}"
          state: directory

      - name: Check if keys exist
        shell: "find {{ playbook_dir }}/files/ssh-keys/{{ DEST }} -name '*key*' | wc -l"
        register: ssh_keys_exists
        changed_when: false

      - debug:
          msg: "Number of keys found: {{ ssh_keys_exists.stdout }}"

      - name: Generate SSH host keys
        command: ssh-keygen -t {{ item }} -N "" -f {{ playbook_dir }}/files/ssh-keys/{{ DEST }}/ssh_host_{{ item }}_key
        with_items:
          - rsa
          - ecdsa
          - ed25519
        when: ssh_keys_exists.stdout | trim | int != 6

      - name: Change {{ playbook_dir }}/files/ssh-keys/{{ DEST }} owner to {{ ansible_env.USER }}
        shell: "chown {{ ansible_env.USER }}:{{ ansible_env.USER }} {{ playbook_dir }}/files/ssh-keys/{{ DEST }}/*"
        register: ssh_key_files


      - name: Change keys permissions before copy
        shell: "chmod 644 {{ playbook_dir }}/files/ssh-keys/{{ DEST }}/*"
        register: ssh_key_files

      - name: Ensure the directory for SSH shared keys exists
        file:
          path: "{{ playbook_dir }}/files/ssh-keys/shared"
          state: directory

      - name: Check if shared keys exist
        shell: "find {{ playbook_dir }}/files/ssh-keys/shared/ -name 'id_rsa_lxc*' | wc -l"
        register: ssh_shared_keys_exists
        changed_when: false

      - debug:
          msg: "Number of shared keys found: {{ ssh_shared_keys_exists.stdout }}"

      - name: Generate SSH shared keys
        command: ssh-keygen -t rsa -N "" -f {{ playbook_dir }}/files/ssh-keys/shared/id_rsa_lxc
        when: ssh_shared_keys_exists.stdout | trim | int != 2

      - name: Change keys permissions before copy
        shell: "chmod 644 {{ playbook_dir }}/files/ssh-keys/shared/*"
        register: ssh_key_files


      - name: Check if {{ DEST }} container exists
        command: lxc-ls -f | grep {{ DEST }}
        register: tsc_exists
        ignore_errors: yes

      - name: Variable tsc_exists
        debug:
          msg: "{{ tsc_exists }}"

      - name: Check if {{ DEST }} container is running
        command: lxc-ls -f --running | grep {{ DEST }}
        register: container_status
        ignore_errors: yes
        when: tsc_exists.rc == 0

     - name: Output value of container_status
       debug:
         var: container_status

      - name: Stop {{ DEST }} container if it is running
        command: lxc-stop -n {{ DEST }}
        ignore_errors: yes
        when: container_status.stdout != "" and  DEST in container_status.stdout_lines

      - name: Pause for 5 seconds
        wait_for:
          delay: 1
          timeout: 5

      - name: Destroy {{ DEST }} container if it exists
        command: lxc-destroy -n {{ DEST }}
        when: DEST in tsc_exists.stdout

      - name: Create directory for {{ DEST }} container
        file:
          path: /var/lib/lxc/{{ DEST }}
          state: directory

      - name: Check if {{ DEST }} container exists
        command: lxc-ls --fancy
        register: lxc_list

      - name: Create LXC container {{ DEST }} if it does not exist
        command: lxc-create --name {{ DEST }} --template download -- --dist debian --release bookworm --arch amd64
        when: "DEST not in lxc_list.stdout"

      - name: Get IP for {{ DEST }} from inventory
        shell: "grep {{ DEST }}.*ansible_hosts {{ hostvars[inventory_hostname]['ansible_inventory_sources'][0] }} | awk -F'=' '{print $2}'"
        register: tsc_ip_output

      - name: Print the IP of {{ DEST }}
        debug:
          msg: "IP of {{ DEST }}: {{ tsc_ip_output.stdout }}"

      - name: Remove static DHCP entries for {{ tsc_ip_output.stdout }} in dnsmasq.conf
        lineinfile:
          path: /etc/lxc/dnsmasq.conf
          state: absent
          regexp: '^dhcp-host=.*{{ tsc_ip_output.stdout }}.*'

      - name: Set static DHCP for {{ DEST }} in dnsmasq.conf
        lineinfile:
          path: /etc/lxc/dnsmasq.conf
          line: "dhcp-host={{ DEST }},{{ tsc_ip_output.stdout }}"

      - name: Create symlink for dnsmasq.conf
        file:
          src: /etc/lxc/dnsmasq.conf
          dest: /etc/dnsmasq.d/lxc.conf
          state: link

      - name: Remove lines containing {{ DEST }} from dnsmasq leases file
        command: sed -i '/{{ DEST }}/d' /var/lib/misc/dnsmasq.lxcbr0.leases

      - name: Restart lxc-net service
        systemd:
          name: lxc-net
          state: restarted

      - name: Start LXC container {{ DEST }}
        command: lxc-start -n {{ DEST }}
        when: "DEST not in lxc_list.stdout"

      - name: Check if {{ DEST }} container is running
        command: lxc-info -n {{ DEST }} -s
        register: container_status
        ignore_errors: true

      - name: Install OpenSSH server in {{ DEST }}
        command: lxc-attach -n {{ DEST }} -- apt-get install -y openssh-server
        when: container_status.rc == 0

      - name: Install Python3 in {{ DEST }}
        command: lxc-attach -n {{ DEST }} -- apt-get install -y python3 python-apt-common
        when: container_status.rc == 0

      # - name: Copy SSH host keys to {{ DEST }}
      #   command: lxc-file push {{ playbook_dir }}/files/ssh-keys/{{ DEST }}/* {{ DEST }}/etc/ssh/
      #   when: container_status.rc == 0

      - name: Get list of SSH host keys
        shell: "find {{ playbook_dir }}/files/ssh-keys/{{ DEST }} -name '*key*'"
        register: ssh_key_files

      - name: Copy SSH host keys to /var/lib/lxc/{{ DEST }}/rootfs/etc/ssh/
        copy:
          src: "{{ item }}"
          dest: "/var/lib/lxc/{{ DEST }}/rootfs/etc/ssh/"
          owner: root
          group: root
          mode: '0600'
        with_items: "{{ ssh_key_files.stdout_lines }}"

      - name: Change keys permissions after copy
        shell: "chmod 600 {{ playbook_dir }}/files/ssh-keys/shared/*"
        register: ssh_key_files

      - name: Change keys permissions after copy
        shell: "chmod 644 {{ playbook_dir }}/files/ssh-keys/shared/*pub"
        register: ssh_key_files

      - name: Change public keys permissions after copy
        shell: "chmod 644 /var/lib/lxc/{{ DEST }}/rootfs/etc/ssh/*pub"

      - name: Restart SSH service in {{ DEST }}
        command: lxc-attach -n {{ DEST }} -- /etc/init.d/ssh restart

      - name: Set root password for {{ DEST }}
        command: lxc-attach -n {{ DEST }} -- sh -c "echo 'root:finiquito' | chpasswd"

      - name: Create user {{ lxc_username }}
        command: lxc-attach -n {{ DEST }} -- adduser --disabled-password --gecos "" --uid 1015 {{ lxc_username }}

      - name: Create group inside container (GID 300)
        command: lxc-attach -n {{ DEST }} -- bash -c "groupadd -g 300 devpl"

      - name: Create user {{ lxc_username }} with password
        command: lxc-attach -n {{ DEST }} -- sh -c "echo '{{ lxc_username }}:{{ lxc_username }}' | chpasswd"

      - name: Add user {{ lxc_username }} to the devpl group
        command: lxc-attach -n {{ DEST }} -- usermod -aG devpl {{ lxc_username }}

      - name: create git-carlos
        command: lxc-attach -n {{ DEST }} -- mkdir -p /home/{{ lxc_username }}/git-carlos/git-hub

      - name: chown git-carlos
        command: lxc-attach -n {{ DEST }} -- chown -R {{ lxc_username }}:{{ lxc_username }} /home/{{ lxc_username }}/git-carlos

      - name: create data
        command: lxc-attach -n {{ DEST }} -- mkdir -p /home/{{ lxc_username }}/data

      - name: chown git-carlos
        command: lxc-attach -n {{ DEST }} -- chown -R {{ lxc_username }}:{{ lxc_username }} /home/{{ lxc_username }}/data

      - name: Add user {{ lxc_username }} to the sudo group
        command: lxc-attach -n {{ DEST }} -- usermod -aG sudo {{ lxc_username }}

      - name: Allow members of the sudo group to run sudo without a password
        become: yes
        become_method: sudo
        lineinfile:
          path:  "/var/lib/lxc/{{ DEST }}/rootfs/etc/sudoers"
          regexp: '^%sudo'
          line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'

      - name: Restart sudo
        command: lxc-attach -n {{ DEST }} -- /etc/init.d/sudo restart

      - name: Create dir /home/{{ lxc_username }}/.ssh
        command: lxc-attach -n {{ DEST }} -- sh -c "mkdir -p /home/{{ lxc_username }}/.ssh; chown -R {{ lxc_username }}:{{ lxc_username }} /home/{{ lxc_username }}/.ssh"

      - name: Get list of SSH shared keys
        shell: "find {{ playbook_dir }}/files/ssh-keys/shared -name 'id_rsa_lxc*'"
        register: ssh_shared_keys_files

      - name: Copy SSH shared keys to /var/lib/lxc/{{ DEST }}/rootfs/home/{{ lxc_username }}/.ssh/
        copy:
          src: "{{ item }}"
          dest: "/var/lib/lxc/{{ DEST }}/rootfs/home/{{ lxc_username }}/.ssh/"
          owner: root
          group: root
          mode: '0600'
        with_items: "{{ ssh_shared_keys_files.stdout_lines }}"

      - name: Change public keys permissions after copy
        shell: "chmod 644 /var/lib/lxc/{{ DEST }}/rootfs/home/{{ lxc_username }}/.ssh/*pub"

      - name: Generate authorized_keys
        command: lxc-attach -n {{ DEST }} -- sh -c "cat /home/{{ lxc_username }}/.ssh/id_rsa_lxc.pub > /home/{{ lxc_username }}/.ssh/authorized_keys; chmod 600  /home/{{ lxc_username }}/.ssh/authorized_keys"

      - name: Create dir /home/concesion/.ssh
        command: lxc-attach -n {{ DEST }} -- sh -c "chown -R {{ lxc_username }}:{{ lxc_username }} /home/{{ lxc_username }}/.ssh"

      - name: Install packages (batch 1)
        command: lxc-attach -n {{ DEST }} -- sh -c "apt-get install -y {{ item }}"
        loop:
          - wget
          - curl

      - name: Remove sources.list file from {{ DEST }}
        command: lxc-attach -n {{ DEST }} -- rm -f /etc/apt/sources.list

      - name: Set sources lists
        command: lxc-attach -n {{ DEST }} -- sh -c "echo {{ item }} >> /etc/apt/sources.list"
        loop:
          - "# generated by ansible"
          - "deb http://deb.debian.org/debian/ bookworm main contrib non-free-firmware"
          - "deb-src http://deb.debian.org/debian/ bookworm main contrib non-free-firmware"
          - "deb http://security.debian.org/debian-security bookworm-security main contrib non-free-firmware"
          - "deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free-firmware"
          - "deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free-firmware"
          - "deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free-firmware"

      # - name: Get keys for web.deb-multimedia.org
      #   command: lxc-attach -n {{ DEST }} -- sh -c "wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb; dpkg -i deb-multimedia-keyring_2016.8.1_all.deb"

      - name: Update sources
        command: lxc-attach -n {{ DEST }} -- sh -c "apt-get update"

      # - name: Add mount entry to git-carlos
      #   lineinfile:
      #     path: /var/lib/lxc/{{ DEST }}/config
      #     line: "lxc.mount.entry = /home/sice/git-sice home/{{ lxc_username }}/git-carlos none bind 0 0"
      #     create: yes # Create the file if it doesn't exist
      #     state: present # Ensure the line is present


      - name: Let data be mounted in the LXC container
        lineinfile:
          path: "/var/lib/lxc/{{ DEST }}/config"
          line: "lxc.mount.entry = /home/{{ lxc_username }}/data/Traefik_LXC home/{{ lxc_username }}/data none bind 0 0"
          state: present

      - name: Add mount entry to git-hub
        lineinfile:
          path: /var/lib/lxc/{{ DEST }}/config
          line: "lxc.mount.entry = /home/{{lxc_username}}/git-carlos/git-hub home/{{ lxc_username }}/git-carlos/git-hub none bind 0 0"
          create: yes # Create the file if it doesn't exist
          state: present # Ensure the line is present

      - name: Stop {{ DEST }} container if it is running
        command: lxc-stop -n {{ DEST }}
        ignore_errors: yes

      - name: Pause for 5 seconds
        wait_for:
          delay: 1
          timeout: 5

      - name: Remove lines containing {{ DEST }} from dnsmasq leases file
        command: sed -i '/{{ DEST }}/d' /var/lib/misc/dnsmasq.lxcbr0.leases

      - name: Restart lxc-net service
        systemd:
          name: lxc-net
          state: restarted

      - name: Pause for 10 seconds
        wait_for:
          delay: 1
          timeout: 3

      - name: Start LXC container {{ DEST }}
        command: lxc-start {{ DEST }}

      - name: Pause for 5 seconds
        wait_for:
          delay: 1
          timeout: 5


      - name: List all LXC containers
        command: lxc-ls -f
        register: lxc_list_final

      - name: Display all LXC containers
        debug:
          var: lxc_list_final.stdout_lines
